2021-10-18 19:18:01,874 DEBUG decos.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2021-10-18 19:18:01,874 DEBUG decos.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2021-10-18 19:18:01,875 DEBUG decos.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2021-10-18 19:18:01,875 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['H:/Программирование/Основной курс Python/Базы данных и PyQT/Project_Pyqt/QWW/server.py']
2021-10-18 19:18:01,877 DEBUG server.py Аргументы успешно загружены.
2021-10-18 19:18:02,024 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-10-18 19:18:48,064 INFO core.py Установлено соедение с ПК ('127.0.0.1', 63576)
2021-10-18 19:18:48,566 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=144, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63576)>,) , {}. Вызов из модуля common.utils
2021-10-18 19:18:48,566 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1634573928.0955143, 'user': {'account_name': 'vlad', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuQFBj9Hg1O01f47kTRlp\n88c45AoArd+JZ70EN92bpdbR/ZktTkETimyTNauaIo3iVYW/ptzdQLR1X9YGk3Jr\nfw+GkcCQUPpByqWECQ/LqudCi2k3IAQQu8Kh+1pdIhwhVJ/CRk1Pqt0UUYwTDBsN\ng7Lg0mfswhPHCQEKc41WAZjQsFWHkTCOPjEEOepQcC2gowzP0mlqJsl1a5e3zad7\nHCHs/debdWRInNvtYGnEi4Crx49Z2tkowjHEd/5Q6XKp+siDEXaqP5M9wAkbQSJp\nuvFXZGXOF1ipKa7iKiKCFguePWoXhIKotiCHX/2nYocyuxML1AI7MWmCH3NTrotu\nRQIDAQAB\n-----END PUBLIC KEY-----'}}
2021-10-18 19:18:48,566 DEBUG core.py Start auth process for {'account_name': 'vlad', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuQFBj9Hg1O01f47kTRlp\n88c45AoArd+JZ70EN92bpdbR/ZktTkETimyTNauaIo3iVYW/ptzdQLR1X9YGk3Jr\nfw+GkcCQUPpByqWECQ/LqudCi2k3IAQQu8Kh+1pdIhwhVJ/CRk1Pqt0UUYwTDBsN\ng7Lg0mfswhPHCQEKc41WAZjQsFWHkTCOPjEEOepQcC2gowzP0mlqJsl1a5e3zad7\nHCHs/debdWRInNvtYGnEi4Crx49Z2tkowjHEd/5Q6XKp+siDEXaqP5M9wAkbQSJp\nuvFXZGXOF1ipKa7iKiKCFguePWoXhIKotiCHX/2nYocyuxML1AI7MWmCH3NTrotu\nRQIDAQAB\n-----END PUBLIC KEY-----'}
2021-10-18 19:18:48,569 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2021-10-18 19:18:48,569 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=144, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63576)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля common.utils
2021-10-18 19:19:20,887 INFO core.py Установлено соедение с ПК ('127.0.0.1', 63578)
2021-10-18 19:19:21,397 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63578)>,) , {}. Вызов из модуля common.utils
2021-10-18 19:19:21,397 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1634573960.8989358, 'user': {'account_name': 'vlad', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuQFBj9Hg1O01f47kTRlp\n88c45AoArd+JZ70EN92bpdbR/ZktTkETimyTNauaIo3iVYW/ptzdQLR1X9YGk3Jr\nfw+GkcCQUPpByqWECQ/LqudCi2k3IAQQu8Kh+1pdIhwhVJ/CRk1Pqt0UUYwTDBsN\ng7Lg0mfswhPHCQEKc41WAZjQsFWHkTCOPjEEOepQcC2gowzP0mlqJsl1a5e3zad7\nHCHs/debdWRInNvtYGnEi4Crx49Z2tkowjHEd/5Q6XKp+siDEXaqP5M9wAkbQSJp\nuvFXZGXOF1ipKa7iKiKCFguePWoXhIKotiCHX/2nYocyuxML1AI7MWmCH3NTrotu\nRQIDAQAB\n-----END PUBLIC KEY-----'}}
2021-10-18 19:19:21,397 DEBUG core.py Start auth process for {'account_name': 'vlad', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuQFBj9Hg1O01f47kTRlp\n88c45AoArd+JZ70EN92bpdbR/ZktTkETimyTNauaIo3iVYW/ptzdQLR1X9YGk3Jr\nfw+GkcCQUPpByqWECQ/LqudCi2k3IAQQu8Kh+1pdIhwhVJ/CRk1Pqt0UUYwTDBsN\ng7Lg0mfswhPHCQEKc41WAZjQsFWHkTCOPjEEOepQcC2gowzP0mlqJsl1a5e3zad7\nHCHs/debdWRInNvtYGnEi4Crx49Z2tkowjHEd/5Q6XKp+siDEXaqP5M9wAkbQSJp\nuvFXZGXOF1ipKa7iKiKCFguePWoXhIKotiCHX/2nYocyuxML1AI7MWmCH3NTrotu\nRQIDAQAB\n-----END PUBLIC KEY-----'}
2021-10-18 19:19:21,398 DEBUG core.py Correct username, starting passwd check.
2021-10-18 19:19:21,420 DEBUG core.py Auth message = {'response': 511, 'bin': '24fda4a6eccc545dde9292a32a0c76ee565a15322e368c9d70ad94163b26b21109e6a30ab988069b213b37a56b1322e7653d41ff86ab42e6d3c515fa25553388'}
2021-10-18 19:19:21,420 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63578)>, {'response': 511, 'bin': '24fda4a6eccc545dde9292a32a0c76ee565a15322e368c9d70ad94163b26b21109e6a30ab988069b213b37a56b1322e7653d41ff86ab42e6d3c515fa25553388'}) , {}. Вызов из модуля common.utils
2021-10-18 19:19:21,420 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63578)>,) , {}. Вызов из модуля common.utils
2021-10-18 19:19:21,420 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63578)>, {'response': 200}) , {}. Вызов из модуля common.utils
2021-10-18 19:19:22,058 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63578)>,) , {}. Вызов из модуля common.utils
2021-10-18 19:19:22,058 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1634573961.4205694, 'account_name': 'vlad'}
2021-10-18 19:19:22,064 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63578)>, {'response': 202, 'data_list': ['test1', 'test2', 'vlad']}) , {}. Вызов из модуля common.utils
2021-10-18 19:19:22,573 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63578)>,) , {}. Вызов из модуля common.utils
2021-10-18 19:19:22,573 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1634573962.1940093, 'user': 'vlad'}
2021-10-18 19:19:22,576 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63578)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля common.utils
2021-10-18 19:23:13,702 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63578)>,) , {}. Вызов из модуля common.utils
2021-10-18 19:23:13,702 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "H:\Программирование\Основной курс Python\Базы данных и PyQT\Project_Pyqt\QWW\server\core.py", line 87, in run
    get_message(client_with_message), client_with_message)
  File "H:\Программирование\Основной курс Python\Базы данных и PyQT\Project_Pyqt\QWW\common\decos.py", line 29, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "H:\Программирование\Основной курс Python\Базы данных и PyQT\Project_Pyqt\QWW\common\utils.py", line 17, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-10-18 19:23:13,703 INFO core.py Клиент ('127.0.0.1', 63578) отключился от сервера.
